### ISSUE TITLE
Asynchronous execution

### ISSUE THREAD

**Issue by Remicek** [matomo-org/piwik-java-tracker#26]
Is there a version that uses asynchronous and safe thread sending?
Now it looks like sending any request will be blocking the whole application.

**Comment by tholu** [comment]
This is very much needed, good point. Happy to accept a Pull Request for this!

**Comment by elsamuko** [comment]
PR: https://github.com/matomo-org/piwik-java-tracker/pull/30

**Comment by tholu** [comment]
Resolved by #31 - thank you very much @elsamuko !
