### ISSUE TITLE
TLC needed, code is old

### ISSUE THREAD

**Issue by phomlish** [matomo-org/piwik-java-tracker#27]
The code is quite dated and in need of TLC.  Including it in my project causes errors due to old libraries.

I could fix the old libraries and add org.apache.http.impl.nio.client.HttpAsyncClientBuilder but why bother if PiwikRequest is not maintained to accomodae the latest functionality of Matomo?

Is PiwikRequest up to date with respect to Matomo 3.8.0?

**Comment by rafaelorafaelo** [comment]
It would be great to hear from Brett. Dead Links on https://github.com/matomo-org/piwik-java-tracker and missing dependencies on https://matomo.org/blog/2015/11/introducing-piwik-java-tracker/ What's going on?

**Comment by tholu** [comment]
Any update on the status of this? Any alternative implementations in Java?

**Comment by tholu** [comment]
Dependencies cleaned up as suggested in #25 and updated to the latest versions in #29.

**Comment by mattab** [comment]
@tholu @rafaelorafaelo @phomlish Would you be interested to become co-maintainers of this Java Matomo SDK project? would be great to get your help to maintain the project, as Brett has become busy with his work and other projects. Let me know what you think!

**Comment by tholu** [comment]
@mattab Sure, would prefer that to maintaining a fork of it.

**Comment by tholu** [comment]
Closed via #29.
