### ISSUE TITLE
New visit created for each action with userid populated since 3.13

### ISSUE THREAD

**Issue by tolomaus** [matomo-org/piwik-java-tracker#28]
Since upgrading to 3.13 all of the sessions where a user id was set get a new visit created for each action.

I'm using the piwik_java_tracker and looking at the code it puts a new random string the the visitor id of each request. This has worked fine in the past, both when a user id was set and when one was not set.

As a workaround: explicitly setting the visitor id to a hex value derived from the user id whenever a userid is set seems to do the trick.

But ideally it should just follow the same logic as the scenario without a user id. There as well, a unique visitor id is created for each request by the piwik_java_tracker but at least the server side is able to group all actions into one session.

See also https://github.com/matomo-org/matomo/issues/15299

**Comment by mattab** [comment]
Hi @tolomaus Thanks for the suggestion. Maybe you are able to open a Pull request on this project? This would be very helpful and help solve this issue quickly.

**Comment by tolomaus** [comment]
Hello Matthieu,

No problem, but could you explain what should be the logic for populating the visitor id? What I described was just a workaround to avoid the spikes in "new visitors".

**Comment by itmagpro** [comment]
I confirm this problem!

Multiple unique visit for each action for same User ID
https://github.com/matomo-org/matomo/issues/15320

**Comment by mattab** [comment]
@tolomaus @itmagpro Could you please upgrade to Matomo 3.13.1 and confirm whether this is still an issue or not? Thanks for confirming!

**Comment by tolomaus** [comment]
Hi Matthieu,

Thanks for the follow up. I can confirm that since I upgraded last Friday (17/01) the issue is solved.

Many thanks!
